In [1]:
import numpy as np

In [2]:
np.arange(16).reshape((4, 17))

ValueError: cannot reshape array of size 16 into shape (4,17)

In [4]:
A = np.random.rand(5, 5)
A

array([[0.22103585, 0.92197555, 0.3003186 , 0.35680259, 0.6100676 ],
       [0.01195654, 0.21069493, 0.58537587, 0.68543667, 0.16810581],
       [0.06207437, 0.04127033, 0.66011665, 0.96734124, 0.43789256],
       [0.84743175, 0.32199156, 0.8416526 , 0.38007878, 0.05372884],
       [0.81317082, 0.54401179, 0.3165273 , 0.24228716, 0.50496581]])

In [6]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2.19308695,  3.44643506, -1.93734784, -1.34561442,  3.32540146],
       [-0.32285033,  4.57571032, -3.0126913 , -1.31323714,  1.61902219],
       [ 3.9501927 , -9.22571429,  4.767281  ,  4.84448026, -6.35059548],
       [-4.05771137, 10.22646224, -4.46519538, -4.35644655,  5.83345072],
       [ 3.3502788 , -9.60328559,  5.51961976,  2.6352907 , -3.93713782]])

In [8]:
Inv = A @ Ainv
Inv[np.isclose(Inv, 0)] = 0
Inv

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
Inv.shape

(5, 5)